### ISSUE TITLE
Need documentation on `protoc` buildtime dependency

### ISSUE THREAD

**Issue by jpmcb** [google/localtoast#1]
On attempting to build the `localtoast` binary per the README.md instructions from the `v1.1.4.3` code tarball:

```
❯ make
go install google.golang.org/protobuf/cmd/protoc-gen-go
protoc -I=. --go_out=. scannerlib/proto/*.proto
/bin/sh: line 1: protoc: command not found
make: *** [Makefile:5: localtoast] Error 127
```

Seems that it's expected to build the gRPC protos before a build is executed through the `build_protos.sh` script.

It'd be nice if this was documented or if there was a different make target provided that didn't require the protos to be created before the binary is built.

**Comment by jpmcb** [comment]
Ah - might be a simple problem with `protoc` vs `protoc-gen-go` being called. When I look in my go bin after the `go install` in the first step, I see:

```
❯ ls -la
total 23824
drwxr-xr-x. 2 fedora fedora     4096 Sep  6 16:34 .
drwxr-xr-x. 4 fedora fedora     4096 Aug  8 15:56 ..
-rwxr-xr-x. 1 fedora fedora  8481069 Sep  6 17:13 protoc-gen-go
```

**Comment by erikvarga** [comment]
The README [should now have](https://github.com/google/localtoast/commit/2d6177f65d4da6ccc38c0b7ba04dcfa26f795776) information about the build dependencies including `protoc`.
