### ISSUE TITLE
Consider adding `/scannerlib/proto` as part of source control

### ISSUE THREAD

**Issue by jpmcb** [google/localtoast#2]
Currently, in a _clean_ repo state, the Go module has unknown dependencies that exist _only_ after a build has happened (or the `build-proto.sh` script is run):

```
❯ go mod tidy
go: finding module for package github.com/google/localtoast/scannerlib/proto/severity_go_proto
go: finding module for package github.com/google/localtoast/scannerlib/proto/compliance_go_proto
go: finding module for package github.com/google/localtoast/scannerlib/proto/scan_instructions_go_proto
go: finding module for package github.com/google/localtoast/scannerlib/proto/api_go_proto
github.com/google/localtoast imports
        github.com/google/localtoast/scannerlib/proto/api_go_proto: no matching versions for query "latest"
github.com/google/localtoast/configs/genfullconfig/genfullconfiglib imports
        github.com/google/localtoast/scannerlib/proto/compliance_go_proto: no matching versions for query "latest"
github.com/google/localtoast/configs/genfullconfig/genfullconfiglib imports
        github.com/google/localtoast/scannerlib/proto/scan_instructions_go_proto: no matching versions for query "latest"
github.com/google/localtoast/configs tested by
        github.com/google/localtoast/configs.test imports
        github.com/google/localtoast/scannerlib/proto/severity_go_proto: no matching versions for query "latest"

❯ make
./build_protos.sh
--2022-09-06 17:37:44--  https://github.com/grafeas/grafeas/archive/0163b5bb2ff5afbf059ddf472fb4d128faae85e3.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/grafeas/grafeas/tar.gz/0163b5bb2ff5afbf059ddf472fb4d128faae85e3 [following]
--2022-09-06 17:37:45--  https://codeload.github.com/grafeas/grafeas/tar.gz/0163b5bb2ff5afbf059ddf472fb4d128faae85e3
Resolving codeload.github.com (codeload.github.com)... 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘0163b5bb2ff5afbf059ddf472fb4d128faae85e3.tar.gz’

0163b5bb2ff5afbf059ddf472fb4d128faae85e3.tar.gz                        [         <=>                                                                                                                                                  ]   9.24M  5.24MB/s    in 1.8s

2022-09-06 17:37:47 (5.24 MB/s) - ‘0163b5bb2ff5afbf059ddf472fb4d128faae85e3.tar.gz’ saved [9694009]

go build localtoast.go
```

After the fact, go mod is able to resolve the dependencies correctly. Looks like it's primarily the dependency on `github.com/grafeas/grafeas`. This creates an interlinking of code sources in the build tree that do not exist as part of the source control.

Would it be possible to add `github.com/grafeas/grafeas` as part of the source control? Possible as a git submodule or maybe a static code dependency?

This makes building from a airgapped / non-networked environment much more challenging since the entire source code is not in the base repo.

**Comment by jpmcb** [comment]
Hi @erikvarga - any update on this or consideration here?

**Comment by erikvarga** [comment]
Hi, sorry for the late reply

The problem is that the files we import from grafeas and the ones under /scannerlib/proto are .proto files that have to be compiled with `protoc` into .pb.go files before we can link them against the rest of the source code.

The only way we can know about the files in advance is if we kept a precompiled .pb.go file for each .proto file around in the source, which we'd have to remember to update whenever we make changes to the .protos, so it'd add some complexity to the codebase.

**Comment by erikvarga** [comment]
Though while I don't see a good way to fix the `go mod tidy` issue, moving the grafeas deps into a git submodule would fix the non-networked env issue, so that could be a feature for us to consider.

**Comment by erikvarga** [comment]
> moving the grafeas deps into a git submodule would fix the non-networked env issue

Hm, except github [doesn't allow releases](https://github.com/dear-github/dear-github/issues/214) that include submodules, which would make it not possible for people to just download the released .zip and build Localtoast from that :/

**Comment by jpmcb** [comment]
Thanks for getting back to me on this! 

> download the released .zip and build Localtoast from that

That's exactly what I'd like to do (and since the environment this may be compiled on won't have a network, it'd be ideal to have all dependencies right there)

Have you considered dropping compiled binaries into releases? That could be a good first step

**Comment by erikvarga** [comment]
Yeah, I think it should be possible for us to just add compiled binaries to our release

I added a compiled x86-64 binary and the config files to the [latest release](https://github.com/google/localtoast/releases/tag/v1.1.5.1).
